"""add categories count to user table

Revision ID: 9ab7f7971e40
Revises: d425adc69fc1
Create Date: 2024-06-28 14:01:40.499463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab7f7971e40'
down_revision: Union[str, None] = 'd425adc69fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('categories_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'categories_count')
    # ### end Alembic commands ###
